//! `gvm anchor keygen` — generate an Ed25519 keypair for WAL anchor signing.
//!
//! Strategic-5: every WAL anchor record carries an Ed25519 signature
//! produced by a key the operator generates here. Auditors hold only
//! the public half (`.pub` file) and verify anchors offline. Losing
//! the secret means no NEW anchors can be signed under the same
//! `key_id`; rotating to a new `key_id` requires distributing the
//! new public key to auditors. Both consequences are documented in
//! the file headers we write so an operator looking at the file later
//! understands what they're holding.

use anyhow::{bail, Context, Result};
use ed25519_dalek::SigningKey;
use rand::rngs::OsRng;
use std::path::{Path, PathBuf};

use crate::ui::{BOLD, CYAN, DIM, GREEN, RESET, YELLOW};

/// Generate a fresh Ed25519 keypair, write secret to `out` (mode
/// 0600) and public to `<out>.pub` (mode 0644). Returns Err on:
///   * `out` already exists and `force == false` (refuse to clobber)
///   * directory missing / not writable
///   * platform unable to set 0600 mode
///
/// Why TOML for the file format: the project already depends on
/// the `toml` crate, parsing is lossless, and operators looking at
/// the file with a text editor immediately see `key_id`,
/// `algorithm`, `created_at`. Binary formats are denser but
/// opaque; for a single-keypair file that fits in 200 bytes the
/// human-readability win is worth the ~3x size overhead.
pub fn keygen(out: &str, key_id: &str, force: bool) -> Result<()> {
    if key_id.is_empty() {
        bail!("--key-id must not be empty");
    }
    if key_id.contains(char::is_whitespace) {
        bail!(
            "--key-id must not contain whitespace (got {:?}). \
             Use a stable label like \"gvm-prod-1\".",
            key_id
        );
    }

    let secret_path = PathBuf::from(out);
    let public_path = secret_path.with_extension(
        secret_path
            .extension()
            .and_then(|s| s.to_str())
            .map(|e| format!("{}.pub", e))
            .unwrap_or_else(|| "pub".to_string()),
    );

    if !force {
        if secret_path.exists() {
            bail!(
                "{} already exists. Re-run with --force to overwrite \
                 (CAUTION: overwriting invalidates every anchor previously \
                 signed under the existing key_id).",
                secret_path.display()
            );
        }
        if public_path.exists() {
            bail!(
                "{} already exists. Re-run with --force to overwrite.",
                public_path.display()
            );
        }
    }

    if let Some(parent) = secret_path.parent() {
        if !parent.as_os_str().is_empty() && !parent.exists() {
            bail!(
                "parent directory does not exist: {}. \
                 Create it with the right ownership/mode before keygen \
                 (e.g. `sudo install -d -o gvm -g gvm -m 0700 /etc/gvm`).",
                parent.display()
            );
        }
    }

    // OsRng is the recommended source for ed25519-dalek key
    // generation; it pulls from the platform CSPRNG (getrandom on
    // Linux). The library zeroizes its internal scratch on drop,
    // and `SigningKey` carries `ZeroizeOnDrop` so the secret is
    // wiped after we serialize it.
    let signing_key = SigningKey::generate(&mut OsRng);
    let secret_bytes = signing_key.to_bytes();
    let public_bytes = signing_key.verifying_key().to_bytes();
    let secret_hex = hex::encode(secret_bytes);
    let public_hex = hex::encode(public_bytes);

    let now_rfc3339 = chrono::Utc::now().to_rfc3339();

    let secret_toml = format!(
        "# GVM anchor signing key (SECRET)\n\
         #\n\
         # Generated by `gvm anchor keygen`. KEEP THIS FILE 0600 AND\n\
         # OWNED BY THE PROXY USER. Anyone holding `secret_hex` can\n\
         # forge anchors that look authentic to your auditors.\n\
         #\n\
         # Loss of this file means no new anchors can be signed under\n\
         # the same key_id. Rotate to a new key_id and tell auditors\n\
         # the cutover timestamp.\n\
         #\n\
         # Public key (safe to share) is in {}.\n\
         \n\
         key_id = \"{}\"\n\
         algorithm = \"ed25519\"\n\
         secret_hex = \"{}\"\n\
         created_at = \"{}\"\n",
        public_path.display(),
        key_id,
        secret_hex,
        now_rfc3339,
    );

    let public_toml = format!(
        "# GVM anchor signing key (PUBLIC)\n\
         #\n\
         # Distribute this file to auditors via your normal trusted\n\
         # key-distribution channel (signed email, internal PKI, etc.).\n\
         # Verifiers map `key_id` to `public_hex` and use it to check\n\
         # `AnchorSignature::SelfSigned` records in the WAL.\n\
         \n\
         key_id = \"{}\"\n\
         algorithm = \"ed25519\"\n\
         public_hex = \"{}\"\n\
         created_at = \"{}\"\n",
        key_id, public_hex, now_rfc3339,
    );

    write_secret_file(&secret_path, secret_toml.as_bytes())
        .with_context(|| format!("Failed to write secret to {}", secret_path.display()))?;
    write_public_file(&public_path, public_toml.as_bytes())
        .with_context(|| format!("Failed to write public to {}", public_path.display()))?;

    println!();
    println!("  {GREEN}\u{2713}{RESET} {BOLD}Anchor keypair generated{RESET}");
    println!();
    println!("    {DIM}key_id     :{RESET} {CYAN}{}{RESET}", key_id);
    println!(
        "    {DIM}secret     :{RESET} {} {DIM}(mode 0600){RESET}",
        secret_path.display()
    );
    println!(
        "    {DIM}public     :{RESET} {} {DIM}(mode 0644){RESET}",
        public_path.display()
    );
    println!("    {DIM}public hex :{RESET} {DIM}{}{RESET}", public_hex);
    println!();
    println!("  {BOLD}Next steps:{RESET}");
    println!(
        "    1. In proxy.toml: {CYAN}[anchor] enabled = true{RESET} and \
         {CYAN}key_path = \"{}\"{RESET}",
        secret_path.display()
    );
    println!(
        "    2. Distribute {DIM}{}{RESET} to your auditor (only the .pub file).",
        public_path.display()
    );
    println!(
        "    3. {YELLOW}Back up{RESET} the secret somewhere encrypted-at-rest. Loss = forced rotation."
    );
    println!();

    Ok(())
}

#[cfg(unix)]
fn write_secret_file(path: &Path, content: &[u8]) -> Result<()> {
    use std::os::unix::fs::OpenOptionsExt;
    let mut f = std::fs::OpenOptions::new()
        .create(true)
        .write(true)
        .truncate(true)
        .mode(0o600)
        .open(path)?;
    use std::io::Write;
    f.write_all(content)?;
    f.sync_all()?;
    Ok(())
}

#[cfg(not(unix))]
fn write_secret_file(path: &Path, content: &[u8]) -> Result<()> {
    // Best-effort on Windows: write the file but warn that the
    // platform doesn't enforce 0600 the way Unix does. Operators
    // running production on Windows should keep the directory's
    // ACL restricted to the proxy user.
    std::fs::write(path, content)?;
    eprintln!(
        "  {} note: file mode 0600 is a Unix concept; on Windows the file \
         inherits the directory's ACL. Confirm only the proxy account can read it.",
        crate::ui::YELLOW
    );
    Ok(())
}

#[cfg(unix)]
fn write_public_file(path: &Path, content: &[u8]) -> Result<()> {
    use std::os::unix::fs::OpenOptionsExt;
    let mut f = std::fs::OpenOptions::new()
        .create(true)
        .write(true)
        .truncate(true)
        .mode(0o644)
        .open(path)?;
    use std::io::Write;
    f.write_all(content)?;
    f.sync_all()?;
    Ok(())
}

#[cfg(not(unix))]
fn write_public_file(path: &Path, content: &[u8]) -> Result<()> {
    std::fs::write(path, content)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn keygen_creates_secret_and_public_files_with_matching_pubkey() {
        let dir = TempDir::new().unwrap();
        let out = dir.path().join("anchor.key");
        keygen(out.to_str().unwrap(), "test-key", false).expect("keygen succeeds");

        let secret_path = out.clone();
        let public_path = out.with_extension("key.pub");

        assert!(secret_path.exists(), "secret file written");
        assert!(public_path.exists(), "public file written");

        // Both files parse as TOML and carry the same key_id.
        let secret_str = std::fs::read_to_string(&secret_path).unwrap();
        let secret_parsed: gvm_proxy::config::AnchorKeyFile =
            toml::from_str(&secret_str).expect("secret file parses");
        assert_eq!(secret_parsed.key_id, "test-key");

        let public_str = std::fs::read_to_string(&public_path).unwrap();
        assert!(
            public_str.contains("public_hex"),
            "public file has public_hex"
        );
        assert!(public_str.contains("test-key"), "public file has key_id");
        assert!(
            !public_str.contains("secret_hex"),
            "public file MUST NOT contain the secret"
        );

        // Secret file actually decodes to a 32-byte SigningKey, and
        // its derived VerifyingKey matches what we wrote into .pub.
        let secret_bytes = secret_parsed.secret_bytes().unwrap();
        let signing = ed25519_dalek::SigningKey::from_bytes(&secret_bytes);
        let derived_pub_hex = hex::encode(signing.verifying_key().to_bytes());
        assert!(
            public_str.contains(&derived_pub_hex),
            "derived public key must appear in .pub file"
        );
    }

    #[test]
    fn keygen_refuses_to_clobber_existing_secret() {
        let dir = TempDir::new().unwrap();
        let out = dir.path().join("anchor.key");
        keygen(out.to_str().unwrap(), "k1", false).unwrap();
        let err = keygen(out.to_str().unwrap(), "k2", false).unwrap_err();
        assert!(
            err.to_string().contains("already exists"),
            "second keygen without --force must fail loudly: {}",
            err
        );
    }

    #[test]
    fn keygen_rejects_empty_key_id() {
        let dir = TempDir::new().unwrap();
        let out = dir.path().join("anchor.key");
        let err = keygen(out.to_str().unwrap(), "", false).unwrap_err();
        assert!(err.to_string().contains("must not be empty"));
    }

    #[test]
    fn keygen_rejects_whitespace_in_key_id() {
        let dir = TempDir::new().unwrap();
        let out = dir.path().join("anchor.key");
        let err = keygen(out.to_str().unwrap(), "key with space", false).unwrap_err();
        assert!(err.to_string().contains("whitespace"));
    }
}
