//! Main sandbox orchestration: clone, setup, exec.
//!
//! Coordinates namespace creation, mount setup, network configuration,
//! and seccomp application into a single launch sequence.

use crate::capability::which_interpreter;
use crate::mount::setup_mount_namespace;
use crate::namespace::{
    coordination_pipe, sandbox_clone_flags, signal_child_ready, wait_for_parent, write_uid_map,
};
use crate::network::{
    cleanup_host_network, clear_sandbox_state, record_sandbox_state, setup_host_network,
    setup_sandbox_network, VethConfig,
};
use crate::seccomp::{apply_seccomp_filter, count_seccomp_violations};
use crate::tc_filter::{self, TcAttachResult};
use crate::{SandboxConfig, SandboxResult};
use anyhow::{Context, Result};
use nix::sys::wait::{waitpid, WaitStatus};
use std::path::PathBuf;

/// Stack size for the cloned child process (2 MB).
const CHILD_STACK_SIZE: usize = 2 * 1024 * 1024;

/// Launch an agent inside a fully isolated Linux sandbox.
pub fn launch(config: SandboxConfig) -> Result<SandboxResult> {
    let start = std::time::Instant::now();

    // Pre-flight: defensive cleanup of orphaned sandbox resources from previous runs.
    // This prevents stale iptables FORWARD chains or veth interfaces from polluting
    // the host network. Particularly important after SIGKILL'd sandboxes where RAII
    // guards did not run.
    if let Err(e) = crate::network::cleanup_all_orphans() {
        tracing::debug!(error = %e, "Orphan cleanup failed (non-fatal)");
    }

    // Parent-process liveness heartbeat. Defense-in-depth complement to
    // PR_SET_PDEATHSIG: gives the cleanup path a positive liveness
    // signal that survives PID reuse (flock auto-releases on parent
    // death) and detects hung parents (mtime stops advancing).
    // Held via RAII for the duration of `launch` — drops before the
    // function returns, releasing the lockfile cleanly. Acquisition
    // failure is non-fatal: we still launch the sandbox, just without
    // the extra liveness signal (PDEATHSIG remains in place).
    let _heartbeat = match crate::heartbeat::ParentHeartbeat::acquire(std::process::id()) {
        Ok(h) => Some(h),
        Err(e) => {
            tracing::warn!(
                error = %e,
                "Parent heartbeat acquisition failed — continuing without lockfile signal"
            );
            None
        }
    };

    // Pre-flight: resolve interpreter path
    let interpreter_path = which_interpreter(&config.interpreter)
        .with_context(|| format!("Interpreter '{}' not found in PATH", config.interpreter))?;

    // CA certificate for MITM trust store injection.
    // The CA is generated by the proxy process (main.rs) which holds the private key.
    // The sandbox only receives the public certificate via SandboxConfig.mitm_ca_cert,
    // downloaded from GET /gvm/ca.pem by the CLI before sandbox launch.
    // This ensures: (1) CA matches the MITM listener's signing key, (2) private key
    // never enters the sandbox namespace.
    let ca_cert_pem: Option<Vec<u8>> = config.mitm_ca_cert.clone();

    // Pre-resolve lib-dynload dependencies in the PARENT process.
    // Running ldd from PID 1 of a new PID namespace triggers kernel panic on 6.17.0-1009-aws.
    let extra_lib_paths = if std::env::var("GVM_DEBUG_SKIP_DYNLOAD").is_ok() {
        Vec::new()
    } else {
        crate::mount::resolve_dynload_libs(&interpreter_path)
    };

    // Pre-mount workspace in parent process BEFORE clone().
    // Kernel 6.17+ blocks bind-mount of host paths inside user namespaces.
    // By mounting in the parent (which has real root), the mount is visible
    // to the child's mount namespace via inheritance.
    // Use PID-based unique paths to prevent race conditions when multiple
    // sandboxes start concurrently. Previous hardcoded paths caused mount
    // collisions: sandbox A mounts → sandbox B umounts A's mount → A's child
    // sees empty root.
    let my_pid = std::process::id();
    // Use /run/gvm/ (root-owned tmpfs) instead of /tmp to prevent symlink attacks.
    // /run/gvm/ is immune to TOCTOU because unprivileged users cannot create
    // entries in it, and tmpfs ensures automatic cleanup on reboot.
    std::fs::create_dir_all("/run/gvm").ok();
    let staging_ws = std::path::PathBuf::from(format!("/run/gvm/sandbox-staging-ws-{}", my_pid));
    let sandbox_root = std::path::PathBuf::from(format!("/run/gvm/sandbox-root-{}", my_pid));
    // Clean up any stale mounts from a previous crashed run.
    // umount2 with MNT_DETACH handles the recursive case (nested mounts).
    // Use rmdir (not remove_dir_all) — see data-loss bug note below at
    // the post-run cleanup site. Same reasoning applies here: the
    // sandbox_root path from a crashed run may still have active
    // bind/overlay mounts pointing at the host workspace; a recursive
    // delete would walk through those mounts and destroy the host tree.
    nix::mount::umount2(&sandbox_root, nix::mount::MntFlags::MNT_DETACH).ok();
    std::fs::remove_dir(&sandbox_root).ok();
    nix::mount::umount(&staging_ws).ok();
    std::fs::create_dir_all(&staging_ws).context("Failed to create workspace staging directory")?;
    nix::mount::mount(
        Some(&config.workspace_dir),
        &staging_ws,
        None::<&str>,
        nix::mount::MsFlags::MS_BIND | nix::mount::MsFlags::MS_REC,
        None::<&str>,
    )
    .with_context(|| {
        format!(
            "Failed to pre-mount workspace in parent: {} → {}",
            config.workspace_dir.display(),
            staging_ws.display()
        )
    })?;

    // Mount overlayfs for $HOME in PARENT process (real root).
    // Parent (real root) can mount overlayfs without UID restrictions.
    // lower=$HOME (read-only), upper=tmpfs (ephemeral writes).
    // Child inherits via clone() and bind-mounts merged → /home/agent.
    let host_home: Option<PathBuf> = std::env::var("SUDO_USER")
        .ok()
        .and_then(|user| {
            std::process::Command::new("getent")
                .args(["passwd", &user])
                .output()
                .ok()
                .and_then(|o| {
                    let s = String::from_utf8_lossy(&o.stdout);
                    s.split(':').nth(5).map(|h| PathBuf::from(h.trim()))
                })
        })
        .or_else(|| std::env::var("HOME").ok().map(PathBuf::from))
        .filter(|p| p.exists());

    let home_overlay_merged: Option<PathBuf> = host_home
        .as_ref()
        .and_then(|home| crate::mount::mount_home_overlay(home, my_pid));

    if let Some(ref m) = home_overlay_merged {
        tracing::debug!(merged = %m.display(), "Home overlayfs mounted by parent");
    }

    // Mount workspace overlayfs in parent if --fs-governance is active.
    // Parent mounts so upper layer survives child exit (same pattern as $HOME overlay).
    // Child inherits via clone() and bind-mounts merged → /workspace.
    let ws_overlay: Option<(PathBuf, PathBuf)> = config.fs_policy.as_ref().and_then(|policy| {
        crate::mount::mount_workspace_overlay(&config.workspace_dir, my_pid, policy.upper_size_mb)
    });
    if let Some((ref merged, ref upper)) = ws_overlay {
        tracing::debug!(
            merged = %merged.display(), upper = %upper.display(),
            "Workspace overlayfs mounted by parent (Trust-on-Pattern)"
        );
    }

    // Create coordination pipe
    let (parent_fd, child_fd) = coordination_pipe()?;

    // Allocate child stack
    let mut stack = vec![0u8; CHILD_STACK_SIZE];
    let clone_flags = sandbox_clone_flags();

    // Prepare data for the child closure
    let child_config = config.clone();
    let child_interpreter_path = interpreter_path.clone();
    let child_ca_pem = ca_cert_pem.clone();
    let child_extra_libs = extra_lib_paths;
    let child_home_overlay = home_overlay_merged.clone();
    let child_ws_overlay = ws_overlay.as_ref().map(|(m, _)| m.clone());

    // SAFETY: nix::sched::clone is unsafe because the child runs on the
    // provided stack with the captured closure; we satisfy the contract by:
    //   * passing a freshly-allocated, sufficiently-large `stack` (CHILD_STACK_SIZE)
    //     that lives until clone() returns to the parent;
    //   * boxing the closure so the child has a stable callable until exit;
    //   * the child only calls async-signal-safe-acceptable functions until
    //     its own exec/exit (see child_entry contract).
    let child_pid = unsafe {
        nix::sched::clone(
            Box::new(move || {
                // ── Child process (inside new namespaces) ──
                child_entry(
                    child_fd,
                    &child_config,
                    &child_interpreter_path,
                    child_ca_pem.as_deref(),
                    &child_extra_libs,
                    child_home_overlay.as_deref(),
                    child_ws_overlay.as_deref(),
                )
            }),
            &mut stack,
            clone_flags,
            Some(nix::sys::signal::SIGCHLD as i32),
        )
    }
    .context("clone() failed — ensure user namespaces are enabled")?;

    tracing::info!(
        child_pid = child_pid.as_raw(),
        "Sandbox child process created"
    );

    // ── Parent process: set up UID mapping and network ──

    // 1. Write UID/GID mapping (only needed when CLONE_NEWUSER is active)
    if !nix::unistd::geteuid().is_root() {
        write_uid_map(child_pid)?;
    }

    // 2. Set up veth network pair (monotonic counter — no PID-based IP collisions)
    let veth_config = VethConfig::new(child_pid.as_raw() as u32, config.proxy_addr);
    let network_result = setup_host_network(&veth_config);

    // dns_target is recorded in state file for deterministic cleanup.
    // If DNS changes between setup and cleanup (DHCP renewal), cleanup
    // still deletes the exact DNAT rule that was created.
    let dns_target = match &network_result {
        Ok(dns) => Some(dns.clone()),
        Err(e) => {
            tracing::warn!(error = %e, "Host network setup failed — sandbox will have no network");
            None
        }
    };

    if network_result.is_ok() {
        let mut mount_paths = vec![staging_ws.clone(), sandbox_root.clone()];
        if let Some(ref m) = home_overlay_merged {
            mount_paths.push(m.clone());
            mount_paths.push(PathBuf::from(format!("/run/gvm/home-overlay-{}", my_pid)));
        }
        if let Some((ref merged, _)) = ws_overlay {
            mount_paths.push(merged.clone());
            mount_paths.push(PathBuf::from(format!("/run/gvm/ws-overlay-{}", my_pid)));
        }
        if let Err(e) =
            record_sandbox_state(&veth_config, &mount_paths, None, dns_target.as_deref())
        {
            tracing::debug!(error = %e, "Failed to record sandbox state (orphan cleanup unavailable)");
        }
    }
    // 2.5. Attach TC ingress filter on host-side veth (unbypassable enforcement)
    //      This runs BEFORE signaling the child, so enforcement is active from first packet.
    //      If TC filter is unavailable, iptables provides baseline enforcement and
    //      seccomp AF_NETLINK blocking prevents iptables modification (defense-in-depth).
    // RAII guard: dropping this detaches the TC filter. Kept alive for sandbox duration.
    let _tc_guard = if network_result.is_ok() {
        let proxy_ip: std::net::Ipv4Addr = veth_config
            .host_ip
            .parse()
            .unwrap_or(std::net::Ipv4Addr::new(10, 200, 0, 1));
        match tc_filter::try_attach_tc_filter(
            &veth_config.host_iface,
            proxy_ip,
            veth_config.proxy_addr.port(),
        ) {
            TcAttachResult::Attached { interface, guard } => {
                tracing::info!(
                    interface = %interface,
                    "TC ingress filter ACTIVE — unbypassable proxy enforcement"
                );
                Some(guard)
            }
            TcAttachResult::Unavailable { reason } => {
                tracing::warn!(
                    reason = %reason,
                    "TC ingress filter unavailable — using iptables with seccomp defense-in-depth"
                );
                None
            }
        }
    } else {
        None
    };

    // 2.7. Set up cgroup resource limits (if configured)
    let _cgroup_guard = if config.memory_limit.is_some() || config.cpu_limit.is_some() {
        match crate::cgroup::CgroupGuard::create(
            child_pid.as_raw() as u32,
            config.memory_limit,
            config.cpu_limit,
        ) {
            Ok(guard) => {
                // Update state file with cgroup path
                if let Some(ref g) = guard {
                    let mount_paths = vec![staging_ws.clone(), sandbox_root.clone()];
                    let cgroup_path = format!("/sys/fs/cgroup/gvm-agent-{}", child_pid.as_raw());
                    if let Err(e) = record_sandbox_state(
                        &veth_config,
                        &mount_paths,
                        Some(&cgroup_path),
                        dns_target.as_deref(),
                    ) {
                        tracing::debug!(error = %e, "Failed to update state with cgroup");
                    }
                    let _ = g; // suppress unused warning
                }
                guard
            }
            Err(e) => {
                tracing::warn!(error = %e, "cgroup setup failed — continuing without resource limits");
                None
            }
        }
    } else {
        None
    };

    // 3. Signal child that setup is complete.
    // Send the veth slot (not child PID) so the child reconstructs matching addresses.
    signal_child_ready(parent_fd, veth_config.slot)?;

    let setup_ms = start.elapsed().as_millis() as u64;
    tracing::info!(
        setup_ms = setup_ms,
        "Sandbox setup complete, waiting for agent"
    );

    // 4. Wait for child to exit with timeout + termination signal awareness.
    //
    // The WNOHANG polling loop serves three purposes:
    // a) Timeout: kill child after GVM_SANDBOX_TIMEOUT
    // b) User termination: detect parent-bound SIGTERM/SIGINT/SIGHUP via flag
    // c) Cleanup guarantee: always reach cleanup code (step 5) even if
    //    the tokio runtime is shutting down, because this runs in spawn_blocking
    //
    // Termination detection: we install a single flag-setting handler on
    // three signals — SIGTERM (systemd stop, `gvm stop`, stress-test kill),
    // SIGINT (user Ctrl+C at the terminal), and SIGHUP (SSH disconnect /
    // controlling tty closed). All three indicate "operator wants us gone".
    // The polling loop sees the flag, gracefully kills the child, and falls
    // through to cleanup — preventing orphan veths, iptables chains, mounts,
    // cgroups, and state files. Without SIGINT coverage, Ctrl+C during a
    // sandbox run would leave the runtime crashing through Rust's default
    // signal handling before cleanup could run, forcing the next launch to
    // pick up the mess via cleanup_all_orphans().
    //
    // SIGKILL is unrecoverable by design — no userspace handler runs for it.
    // The safety net for -9 is the orphan sweep at the top of launch().
    use std::sync::atomic::Ordering;

    // Install single handler on SIGTERM + SIGINT + SIGHUP (sets TERMINATION_FLAG)
    TERMINATION_FLAG.store(false, Ordering::Relaxed); // Reset for this sandbox run
    TERMINATION_SIGNAL.store(0, Ordering::Relaxed);
    // SAFETY: termination_flag_handler is an `extern "C"` function with the
    // exact signal-handler signature; casting via *const () to sighandler_t
    // is the libc-conventional way to install a handler. The function only
    // touches AtomicBool/AtomicI32, both async-signal-safe.
    unsafe {
        let handler = termination_flag_handler as *const () as libc::sighandler_t;
        libc::signal(libc::SIGTERM, handler);
        libc::signal(libc::SIGINT, handler);
        libc::signal(libc::SIGHUP, handler);
    }

    let wait_timeout = std::time::Duration::from_secs(
        std::env::var("GVM_SANDBOX_TIMEOUT")
            .ok()
            .and_then(|s| s.parse().ok())
            .unwrap_or(3600), // Default: 1 hour
    );
    let wait_start = std::time::Instant::now();
    // Track which path triggered SIGKILL so we can classify SIGKILL exits
    // by root cause (Timeout vs SIGTERM-relayed-as-SIGKILL vs OOM vs external).
    let mut timeout_triggered = false;
    let mut user_interrupt_triggered = false;
    let wait_result = loop {
        match waitpid(child_pid, Some(nix::sys::wait::WaitPidFlag::WNOHANG)) {
            Ok(WaitStatus::StillAlive) => {
                // Check SIGTERM — kill child gracefully and proceed to cleanup
                if TERMINATION_FLAG.load(Ordering::Relaxed) {
                    tracing::info!(
                        pid = child_pid.as_raw(),
                        "Termination signal received (SIGTERM/SIGINT/SIGHUP) — killing sandbox child for cleanup"
                    );
                    user_interrupt_triggered = true;
                    nix::sys::signal::kill(child_pid, nix::sys::signal::SIGTERM).ok();
                    std::thread::sleep(std::time::Duration::from_millis(500));
                    nix::sys::signal::kill(child_pid, nix::sys::signal::SIGKILL).ok();
                    break waitpid(child_pid, None);
                }

                // timeout=0 means no timeout (persistent sandbox).
                // Agent runs until it exits or SIGTERM is received.
                if wait_timeout.as_secs() > 0 && wait_start.elapsed() > wait_timeout {
                    tracing::warn!(
                        pid = child_pid.as_raw(),
                        timeout_secs = wait_timeout.as_secs(),
                        "Sandbox child timed out — sending SIGKILL"
                    );
                    timeout_triggered = true;
                    nix::sys::signal::kill(child_pid, nix::sys::signal::SIGKILL).ok();
                    break waitpid(child_pid, None);
                }
                std::thread::sleep(std::time::Duration::from_millis(200));
                continue;
            }
            result => break result,
        }
    };
    let seccomp_violations = match &wait_result {
        Ok(status) => count_seccomp_violations(status),
        Err(_) => 0,
    };

    // Read cgroup observability counters BEFORE the cgroup guard is dropped.
    // memory.oom.group=1 ensures all cgroup processes are reaped before SIGCHLD,
    // so by the time waitpid returns, oom_kill counter is final and stable.
    let oom_kills = _cgroup_guard
        .as_ref()
        .map(|g| g.oom_kill_count())
        .unwrap_or(0);
    let cpu_throttled_us = _cgroup_guard.as_ref().and_then(|g| g.cpu_throttled_us());
    let memory_limit_mb = config.memory_limit.map(|b| b / (1024 * 1024));

    let (exit_code, exit_reason) = match wait_result {
        Ok(WaitStatus::Exited(_, 0)) => (0, crate::ExitReason::Normal),
        Ok(WaitStatus::Exited(_, code)) => (code, crate::ExitReason::AgentError { code }),
        Ok(WaitStatus::Signaled(_, signal, _)) => {
            let signum = signal as i32;
            // SIGKILL classification priority (root cause first):
            //   1. OOM kill (kernel-initiated, cgroup memory.events evidence)
            //   2. Timeout (GVM-initiated, wait loop set the flag)
            //   3. UserInterrupt (GVM-initiated, SIGTERM relayed)
            //   4. SeccompViolation (SIGSYS specifically)
            //   5. ExternalKill (anything else)
            let reason = if signal == nix::sys::signal::Signal::SIGSYS {
                // Best-effort: scan kernel ring buffer for the AUDIT_SECCOMP
                // record matching this child PID. The record is emitted by
                // our dual-filter Log layer, so it exists whenever the agent
                // tripped the filter — but only if dmesg is readable (root
                // or `kernel.dmesg_restrict=0`). Graceful fallback to None.
                let syscall =
                    crate::seccomp_audit::find_syscall_name_for_pid(child_pid.as_raw() as u32);
                crate::ExitReason::SeccompViolation {
                    count: seccomp_violations.max(1),
                    syscall,
                }
            } else if oom_kills > 0 {
                crate::ExitReason::OomKill { memory_limit_mb }
            } else if timeout_triggered {
                crate::ExitReason::Timeout {
                    secs: wait_timeout.as_secs(),
                }
            } else if user_interrupt_triggered {
                let sig = TERMINATION_SIGNAL.load(Ordering::Relaxed);
                let signal_name = match sig {
                    libc::SIGINT => "SIGINT",
                    libc::SIGTERM => "SIGTERM",
                    libc::SIGHUP => "SIGHUP",
                    _ => "unknown",
                };
                crate::ExitReason::UserInterrupt {
                    signal: signal_name,
                }
            } else {
                crate::ExitReason::ExternalKill { signal: signum }
            };
            tracing::warn!(signal = ?signal, reason = ?reason, "Agent killed by signal");
            (128 + signum, reason)
        }
        Ok(status) => {
            tracing::warn!(status = ?status, "Unexpected wait status");
            (1, crate::ExitReason::ExternalKill { signal: 0 })
        }
        Err(e) => {
            tracing::error!(error = %e, "waitpid failed");
            (1, crate::ExitReason::ExternalKill { signal: 0 })
        }
    };

    if seccomp_violations > 0 {
        tracing::error!(
            violations = seccomp_violations,
            child_pid = child_pid.as_raw(),
            "Seccomp violations detected — agent attempted blocked syscall(s). \
             Check 'dmesg | grep SECCOMP' or 'ausearch -m SECCOMP' for details."
        );
    }

    // 5. Scan overlayfs upper layer BEFORE cleanup (tmpfs umount destroys it).
    // Parent-mounted workspace overlay: upper dir is at /run/gvm/ws-overlay-{pid}/upper.
    // Fallback: child-mounted overlay at sandbox_root/gvm-overlay/upper (legacy).
    let fs_diff = {
        let upper_dir = ws_overlay
            .as_ref()
            .map(|(_, u)| u.clone())
            .unwrap_or_else(|| sandbox_root.join("gvm-overlay/upper"));
        if upper_dir.exists() {
            let policy = config.fs_policy.as_ref().cloned().unwrap_or_default();
            match crate::filesystem::scan_upper_layer(&upper_dir, &config.workspace_dir, &policy) {
                Ok(report) => {
                    // Execute auto-merge (Created files only — Modified goes to ManualCommit)
                    if !report.auto_merged.is_empty() {
                        let merge_result = crate::filesystem::execute_merge(
                            &report,
                            &upper_dir,
                            &config.workspace_dir,
                        );
                        tracing::info!(
                            copied = merge_result.copied.len(),
                            skipped = merge_result.skipped.len(),
                            errors = merge_result.errors.len(),
                            "Overlayfs auto-merge completed"
                        );
                    }

                    // Stage needs_review files to persistent storage (before umount).
                    // The interactive review prompt runs in the CLI layer (pipeline.rs)
                    // AFTER sandbox cleanup, so files must be preserved outside tmpfs.
                    if !report.needs_review.is_empty() {
                        let staging_dir =
                            PathBuf::from(format!("data/sandbox-staging/{}", std::process::id()));
                        if std::fs::create_dir_all(&staging_dir).is_ok() {
                            for f in &report.needs_review {
                                let src = upper_dir.join(&f.path);
                                let dst = staging_dir.join(&f.path);
                                if let Some(parent) = dst.parent() {
                                    std::fs::create_dir_all(parent).ok();
                                }
                                std::fs::copy(&src, &dst).ok();
                            }
                            tracing::debug!(
                                count = report.needs_review.len(),
                                staging = %staging_dir.display(),
                                "Staged needs_review files for interactive review"
                            );
                        }
                    }

                    Some(report)
                }
                Err(e) => {
                    tracing::debug!(error = %e, "Overlayfs scan failed (non-fatal)");
                    None
                }
            }
        } else {
            None
        }
    };

    // 6. Clean up host-side resources
    // Unmount sandbox root (lazy detach handles nested mounts from failed runs).
    //
    // CRITICAL — data-loss bug fixed here (2026-04-16):
    // Using `remove_dir_all(&sandbox_root)` after a lazy `MNT_DETACH` is a
    // race that destroys the host workspace. `MNT_DETACH` defers the real
    // unmount until all references drop; if the recursive delete runs
    // before the kernel finishes the detach, it descends INTO the still-
    // mounted `sandbox_root/workspace` (bind to the agent's workspace_dir,
    // i.e. the user's repo) and deletes real files from the host tree.
    //
    // Reproduced 2026-04-16: a single 2-minute `gvm run --sandbox` stress
    // session destroyed 224 files from the repo (src/, fuzz/, .git/, etc.)
    // via this path.
    //
    // Fix: unmount the recursive tree with MNT_DETACH, then use `rmdir`
    // (`remove_dir`, not `remove_dir_all`). rmdir fails closed — if the
    // mount is still live or the directory is non-empty due to the bind
    // not yet being released, it just returns EBUSY/ENOTEMPTY and we
    // leave the empty dir for the next launch's defense sweep to pick up.
    nix::mount::umount2(&sandbox_root, nix::mount::MntFlags::MNT_DETACH).ok();
    std::fs::remove_dir(&sandbox_root).ok();
    // Unmount the staging workspace (pre-mounted before clone for kernel 6.17+ compat).
    // Parent mounted with MS_BIND | MS_REC, so cleanup must use MNT_DETACH to release
    // any nested submounts the recursive bind picked up. A plain umount() leaves the
    // entry in /proc/mounts because the mount has children, which the post-cleanup
    // residual scanner correctly flags.
    nix::mount::umount2(&staging_ws, nix::mount::MntFlags::MNT_DETACH).ok();
    std::fs::remove_dir(&staging_ws).ok();
    // Clean up home overlayfs (parent-mounted before clone)
    crate::mount::cleanup_home_overlay(my_pid);
    // Clean up workspace overlayfs (parent-mounted, scanned in step 5)
    crate::mount::cleanup_workspace_overlay(my_pid);
    // Drop TC filter guard first — this detaches the filter via RAII Drop.
    // Must happen before cleanup_host_network which deletes the veth interface.
    drop(_tc_guard);

    // Always run cleanup, even on partial setup failure.
    //
    // Earlier this gate was `if network_result.is_ok()` — if
    // setup_host_network() returned Err, cleanup was skipped entirely.
    // Two production failure modes that produced silent leaks:
    //
    //   1. Slot-collision retries: setup adds veth pair + first NAT
    //      rule, then a later iptables rule fails (slot already taken,
    //      ip_forward sysctl, etc.). network_result is Err. The gate
    //      skipped cleanup → veth pair AND any added rules leaked.
    //
    //   2. Repeated launches after a crash: previous run left veth-
    //      gvm-h0; new run's setup fails on `ip addr add` because
    //      slot 0 is occupied; gate skips cleanup; the new run's
    //      output says "Cleanup verification: 2 residual(s)" but
    //      doesn't actually remove them — the user has to run
    //      `gvm cleanup` manually. (Discovered by the
    //      Test 10 / Agent SIGTERM matrix scenario.)
    //
    // cleanup_host_network is idempotent: it uses `iptables -D` (with
    // .ok() to swallow "no such rule" errors) and `ip link del` (with
    // .ok() for "no such device"). Calling it always — even when
    // setup didn't reach the point of installing rules — is safe and
    // closes both leak modes.
    //
    // clear_sandbox_state is also idempotent: a no-op if the state
    // file was never written.
    cleanup_host_network(&veth_config, dns_target.as_deref());
    clear_sandbox_state();

    // 7. Verify cleanup actually released everything we claim to have released.
    // Cheap (~tens of ms): one `ip link show`, two iptables calls, one
    // /proc/mounts read, three Path::exists checks. Run unconditionally so
    // any leak is visible to the caller — silent residuals would erode trust
    // in the "Zero-Trace" UX of `gvm stop`.
    let mount_paths_for_verify: Vec<String> = {
        let mut v = vec![
            staging_ws.display().to_string(),
            sandbox_root.display().to_string(),
        ];
        if let Some(ref m) = home_overlay_merged {
            v.push(m.display().to_string());
            v.push(format!("/run/gvm/home-overlay-{}", my_pid));
        }
        v
    };
    let cleanup_verification =
        crate::verify_cleanup(my_pid, &veth_config.host_iface, &mount_paths_for_verify);
    if !cleanup_verification.is_clean() {
        tracing::warn!(
            residuals = cleanup_verification.total(),
            "Post-cleanup residuals detected — see SandboxResult.cleanup_verification"
        );
    }

    Ok(SandboxResult {
        exit_code,
        exit_reason,
        setup_ms,
        seccomp_violations,
        cpu_throttled_us,
        fs_diff,
        cleanup_verification,
    })
}

/// Child process entry point (runs inside new namespaces).
fn child_entry(
    coord_fd: std::os::unix::io::RawFd,
    config: &SandboxConfig,
    interpreter_path: &std::path::Path,
    ca_cert_pem: Option<&[u8]>,
    extra_lib_paths: &[std::path::PathBuf],
    home_overlay_merged: Option<&std::path::Path>,
    ws_overlay_merged: Option<&std::path::Path>,
) -> isize {
    // ── parent-death watchdog ──────────────────────────────────────
    //
    // Purpose: when the gvm CLI parent dies (especially via SIGKILL,
    // kernel OOM-killer, or any path the CLI cannot intercept), the
    // sandbox PID-namespace init MUST die with it. Otherwise the
    // namespace init gets reparented to host PID 1 and keeps running,
    // leaking veth + iptables NAT + state file forever. cleanup
    // logic then sees the namespace init as alive and skips
    // recovery permanently.
    //
    // PR_SET_PDEATHSIG arms the kernel to deliver SIGKILL to THIS
    // process the moment its parent thread terminates. Once we are
    // PID 1 of our own PID namespace, our death triggers a kernel
    // cascade that kills every process inside the namespace — exactly
    // what we need.
    //
    // The "parent" for PDEATHSIG is the thread that called clone(2).
    // gvm-cli runs sandbox launch via tokio::task::spawn_blocking,
    // which dedicates a blocking-pool thread to the launch_sandboxed
    // call for its full duration. That thread persists until the
    // launch returns, so PDEATHSIG firing on its death is correct
    // semantics — it dies precisely when the parent process dies
    // (or completes the sandbox lifecycle gracefully, in which case
    // the cleanup path has already run).
    //
    // Best-effort: if prctl fails (very old kernel / restricted env)
    // we still launch the sandbox. Operators on those kernels lose
    // orphan-prevention but the agent itself works. The lockfile
    // heartbeat (separate fix) provides a second layer of defense.
    // SAFETY: PR_SET_PDEATHSIG only takes integer args; getppid() takes
    // none. Neither dereferences user pointers, and both are safe to call
    // from any context (async-signal-safe in fact).
    unsafe {
        if libc::prctl(libc::PR_SET_PDEATHSIG, libc::SIGKILL, 0, 0, 0) != 0 {
            let err = std::io::Error::last_os_error();
            eprintln!(
                "gvm-sandbox: PR_SET_PDEATHSIG failed: {} \
                 — orphan-prevention disabled for this sandbox",
                err
            );
        }
        // Race guard: if the parent died BETWEEN clone() and the
        // prctl call above, PDEATHSIG never armed and we'd leak.
        // Re-check with getppid() — if we have already been
        // reparented to init(1), suicide instead of running an
        // orphan agent.
        if libc::getppid() == 1 {
            eprintln!("gvm-sandbox: parent died before PDEATHSIG armed — exiting");
            return 1;
        }
    }

    // Wait for parent to complete UID mapping and network setup
    let network_seed = match wait_for_parent(coord_fd) {
        Ok(seed) => seed,
        Err(e) => {
            eprintln!("gvm-sandbox: coordination failed: {}", e);
            return 1;
        }
    };
    // Use parent-provided slot so interface names/IPs match host-side setup.
    let veth_config = VethConfig::from_slot(network_seed, std::process::id(), config.proxy_addr);

    // Set up network inside the sandbox
    if let Err(e) = setup_sandbox_network(&veth_config) {
        // Network failure is non-fatal for debugging — agent just won't have connectivity
        eprintln!("gvm-sandbox: network setup failed (non-fatal): {}", e);
        eprintln!("  Hint: ensure ip_forward=1 (sudo sysctl net.ipv4.ip_forward=1),");
        eprintln!("  iptables installed, and running with sudo (CAP_NET_ADMIN required).");
        eprintln!("  Agent will run without network connectivity.");
    }

    // Set up mount namespace (pivot_root)
    // DNS server must match the OUTPUT iptables rule (host veth IP)
    if let Err(e) = setup_mount_namespace(
        &config.workspace_dir,
        interpreter_path,
        &veth_config.host_ip,
        ca_cert_pem,
        config.fs_policy.as_ref(),
        extra_lib_paths,
        &config.sandbox_profile,
        home_overlay_merged,
        ws_overlay_merged,
    ) {
        eprintln!("gvm-sandbox: mount namespace setup failed: {:#}", e);
        eprintln!("  Hint: this usually means the interpreter binary or its shared");
        eprintln!(
            "  libraries cannot be bind-mounted. Check that '{}' exists",
            config.interpreter
        );
        eprintln!("  and 'ldd {}' succeeds.", interpreter_path.display());
        return 1;
    }

    // Drop all capabilities from the bounding set.
    if let Err(e) = drop_all_capabilities() {
        eprintln!("gvm-sandbox: capability drop failed: {}", e);
        eprintln!("  Hint: this is unusual. Check kernel capabilities support.");
        return 1;
    }
    // Apply seccomp-BPF filter (must be last before exec)
    if let Err(e) = apply_seccomp_filter(&config.seccomp_profile) {
        eprintln!("gvm-sandbox: seccomp filter failed: {}", e);
        eprintln!("  Hint: seccomp-BPF requires kernel 3.17+. Check 'grep SECCOMP /boot/config-$(uname -r)'.");
        return 1;
    }
    // Prepare environment variables
    let proxy_url = format!(
        "http://{}:{}",
        veth_config.host_ip,
        config.proxy_addr.port()
    );

    // Build exec arguments.
    // Remap host paths to sandbox paths. The sandbox overlay mounts the
    // user's home directory under /home/agent, so host paths like
    // /home/ubuntu/hermes-agent/.venv/bin/hermes must become
    // /home/agent/hermes-agent/.venv/bin/hermes.
    // System binaries (in /usr, /bin, /sbin) keep their original paths.
    let bin_path = remap_path_for_sandbox(interpreter_path, &config.interpreter);

    // Set environment and exec
    std::env::set_var("HTTP_PROXY", &proxy_url);
    std::env::set_var("http_proxy", &proxy_url);
    if ca_cert_pem.is_some() {
        // MITM active: don't set HTTPS_PROXY — DNAT handles 443→MITM
        std::env::remove_var("HTTPS_PROXY");
        std::env::remove_var("https_proxy");
    } else {
        // --no-mitm: set HTTPS_PROXY for CONNECT relay (domain-level only)
        std::env::set_var("HTTPS_PROXY", &proxy_url);
        std::env::set_var("https_proxy", &proxy_url);
    }
    // Localhost traffic must bypass the proxy. Agents use loopback for
    // internal services (OpenClaw gateway on :18789, Ollama, local DBs).
    // Without NO_PROXY, HTTP clients send CONNECT 127.0.0.1:443 to the
    // proxy, which fails on MITM (localhost has no valid cert/SNI).
    std::env::set_var("NO_PROXY", "127.0.0.1,localhost,::1");
    std::env::set_var("no_proxy", "127.0.0.1,localhost,::1");
    std::env::set_var("GVM_AGENT_ID", &config.agent_id);
    std::env::set_var("GVM_PROXY_URL", &proxy_url);
    // HOME points to the overlayfs-merged home directory.
    // Agent reads config from host's $HOME (lower layer), writes go to tmpfs
    // (upper layer) and vanish on sandbox exit. Sensitive dirs (.ssh, .aws)
    // are masked with empty tmpfs.
    std::env::set_var("HOME", "/home/agent");
    std::env::set_var("TMPDIR", "/tmp");
    // Disable io_uring in Node.js — forces epoll fallback.
    // io_uring syscalls are not in seccomp whitelist (CVE history).
    // Performance difference is negligible for agent workloads.
    std::env::set_var("UV_USE_IO_URING", "0");

    // NOTE: sandbox inherits ALL parent env vars via clone().
    // If ANTHROPIC_API_KEY etc. are in the parent process, they're available in sandbox.
    // sudo -E may NOT preserve env (sudoers env_reset). Use:
    //   sudo env ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY gvm run --sandbox ...

    // CA trust store env vars (for transparent MITM in sandbox)
    if ca_cert_pem.is_some() {
        let ca_path = "/etc/ssl/certs/gvm-ca.crt";
        std::env::set_var("SSL_CERT_FILE", ca_path);
        std::env::set_var("REQUESTS_CA_BUNDLE", ca_path);
        std::env::set_var("NODE_EXTRA_CA_CERTS", ca_path);
        std::env::set_var("CURL_CA_BUNDLE", ca_path);
    }

    // Placeholder credential env vars — satisfy agent startup validation
    // while the proxy holds the real keys. The proxy strips these placeholders
    // and injects real credentials post-enforcement via secrets.toml.
    for (key, value) in &config.extra_env {
        std::env::set_var(key, value);
    }
    if !config.extra_env.is_empty() {
        tracing::info!(
            count = config.extra_env.len(),
            "Injected {} placeholder credential env var(s) for agent startup",
            config.extra_env.len()
        );
    }

    // Shebang rewriting: if bin_path points to a script whose shebang
    // references a home-directory interpreter (e.g., #!/home/ubuntu/.venv/bin/python),
    // the kernel will fail to exec it because sandbox remapped /home/ubuntu → /home/agent.
    // Detect this and invoke the remapped interpreter directly with the script as arg.
    let (exec_bin, exec_args) = rewrite_shebang_if_needed(&bin_path, &config.interpreter_args);

    // Build argv: [interpreter, ...args]
    // Validate before fork — CString::new fails only on embedded NUL bytes.
    // After fork() we cannot use Rust runtime, so all allocations must happen here.
    let c_bin = match std::ffi::CString::new(exec_bin.clone()) {
        Ok(c) => c,
        Err(e) => {
            eprintln!(
                "gvm-sandbox: interpreter path contains NUL byte: {} ({})",
                exec_bin, e
            );
            return 126; // "command not found" convention
        }
    };
    let mut c_args: Vec<std::ffi::CString> = vec![c_bin.clone()];
    for arg in &exec_args {
        match std::ffi::CString::new(arg.as_str()) {
            Ok(c) => c_args.push(c),
            Err(e) => {
                eprintln!(
                    "gvm-sandbox: interpreter arg contains NUL byte: {} ({})",
                    arg, e
                );
                return 126;
            }
        }
    }

    // ── PID 1 init reaper ──
    //
    // SAFETY INVARIANT (fork + async-signal-safety):
    // After fork(), both child and PID 1 parent MUST only call async-signal-safe
    // functions until exec (child) or _exit (PID 1). This means:
    // - NO Rust heap allocation (no Vec, String, Box, println!, format!)
    // - NO tracing macros (tracing::info! etc. — these allocate)
    // - NO mutex/lock acquisition
    // - NO File I/O via Rust std (only libc::write to fd 2 is safe)
    // Only libc functions listed in signal-safety(7) are permitted.
    // Currently: eprintln! (before fork), waitpid/WIFEXITED/_exit (after fork).
    // Adding any Rust runtime calls to the PID 1 loop WILL cause UB.
    //
    // We are PID 1 inside CLONE_NEWPID. If we exec directly, the agent
    // interpreter becomes PID 1 but does NOT reap orphaned children.
    // When the agent spawns subprocesses (subprocess.Popen, child_process.exec)
    // that exit, they become zombies (Z state). Eventually the PID table fills
    // and the agent can't fork at all.
    //
    // Fix: fork(). The child execs the agent. This process (PID 1) stays alive
    // as a minimal init: it loops on waitpid(-1) to reap ANY child (including
    // orphans reparented to PID 1), and exits with the agent's exit code.
    //
    // This is equivalent to tini/dumb-init but without an external dependency.
    match unsafe { libc::fork() } {
        -1 => {
            // SAFETY: After fork(), only async-signal-safe functions are permitted.
            // Use libc::write to fd 2 (stderr) instead of eprintln! (which allocates).
            unsafe {
                let msg = b"gvm-sandbox: fork() for init reaper failed\n";
                libc::write(2, msg.as_ptr() as *const libc::c_void, msg.len());
            }
            1
        }
        0 => {
            // ── Child: exec the agent ──
            match nix::unistd::execv(&c_bin, &c_args) {
                Ok(_) => unreachable!(),
                Err(_) => {
                    // SAFETY: After fork(), only async-signal-safe.
                    unsafe {
                        let msg = b"gvm-sandbox: exec failed\n";
                        libc::write(2, msg.as_ptr() as *const libc::c_void, msg.len());
                        libc::_exit(1);
                    }
                }
            }
        }
        agent_pid => {
            // ── PID 1 (init reaper): wait for agent + reap orphans ──
            //
            // After the agent exits, its sub-processes (OpenClaw gateway workers,
            // Node.js worker threads, detached children) may still be alive.
            // Without killing them, waitpid(-1) blocks forever — the parent's
            // WNOHANG loop never sees PID 1 exit, causing the sandbox to hang.
            //
            // Fix: once agent exits, SIGTERM → sleep → SIGKILL all remaining
            // children, then continue reaping until ECHILD.
            let mut agent_exit_code: i32 = 1;
            let mut _agent_exited = false;

            loop {
                let mut status: i32 = 0;
                // SAFETY: `&mut status` points to a stack-allocated i32 that
                // lives for this iteration; waitpid() writes through it only
                // after a successful return. -1 is the documented "any child"
                // sentinel.
                let pid = unsafe { libc::waitpid(-1, &mut status, 0) };
                if pid < 0 {
                    // ECHILD: no more children — all reaped
                    break;
                }
                if pid == agent_pid {
                    // Agent exited — record exit code
                    if libc::WIFEXITED(status) {
                        agent_exit_code = libc::WEXITSTATUS(status);
                    } else if libc::WIFSIGNALED(status) {
                        agent_exit_code = 128 + libc::WTERMSIG(status);
                    }
                    _agent_exited = true;

                    // Kill all remaining children in this PID namespace.
                    // kill(-1, sig) sends to all processes except PID 1 (us).
                    // SAFETY: async-signal-safe (kill, nanosleep, write are all safe).
                    unsafe {
                        libc::kill(-1, libc::SIGTERM);
                        // Brief grace period for clean shutdown
                        let ts = libc::timespec {
                            tv_sec: 0,
                            tv_nsec: 500_000_000, // 500ms
                        };
                        libc::nanosleep(&ts, std::ptr::null_mut());
                        libc::kill(-1, libc::SIGKILL);
                    }
                    // Continue reaping until ECHILD
                }
                // Any other PID: orphaned/killed child reaped.
            }

            // Use _exit to avoid running Rust destructors in the clone'd process.
            // SAFETY: _exit() takes an integer status and never returns; no
            // pointers, no allocator interaction. Skipping Rust drop glue is
            // intentional for the cloned init process.
            unsafe { libc::_exit(agent_exit_code) };
        }
    }
}

/// Drop capabilities from the bounding set, keeping only DAC overrides.
///
/// After mount/network setup completes, most capabilities are no longer needed.
/// We keep CAP_DAC_READ_SEARCH and CAP_DAC_OVERRIDE so the capless-root agent
/// can read files with restrictive permissions (e.g., 600 owned by uid 1000
/// in the overlayfs $HOME mount). This matches Docker's default behavior:
/// container root can read all files within the container's filesystem.
///
/// Security model: the sandbox controls WHICH files are exposed (overlayfs
/// lower=$HOME + blocklist masking .ssh/.aws/.gnupg). Within that boundary,
/// the agent has full read access. Write access is controlled by overlayfs
/// (writes go to tmpfs upper layer, host is unmodified).
/// Remap a host binary path to its sandbox-internal equivalent.
///
/// The sandbox overlay remounts the user's home directory under `/home/agent`.
/// Host paths like `/home/ubuntu/hermes-agent/.venv/bin/hermes` must become
/// `/home/agent/hermes-agent/.venv/bin/hermes` for execv to find them.
///
/// System paths (`/usr/bin/python3`, `/bin/bash`) are already correct and
/// pass through unchanged. If the binary is a bare name (`python3`), fall
/// back to `/bin/{name}` for backward compatibility with script-mode
/// interpreter resolution.
fn remap_path_for_sandbox(host_path: &std::path::Path, interpreter_name: &str) -> String {
    let path_str = host_path.to_str().unwrap_or(interpreter_name);

    // Detect home directory prefix: /home/<username>/...
    // The sandbox always mounts the user's home under /home/agent.
    if path_str.starts_with("/home/") {
        // /home/ubuntu/X → /home/agent/X
        // Find the second slash after /home/ to skip the username component.
        if let Some(rest) = path_str
            .strip_prefix("/home/")
            .and_then(|s| s.find('/').map(|i| &s[i..]))
        {
            return format!("/home/agent{}", rest);
        }
    }

    // System paths (/usr/bin/python3, /bin/bash, /usr/local/bin/uv) — keep as-is.
    if path_str.starts_with('/') {
        return path_str.to_string();
    }

    // Bare interpreter name (e.g., "python3") — legacy fallback.
    format!("/bin/{}", interpreter_name)
}

/// If `bin_path` is a script with a shebang that points into a home directory,
/// rewrite it so the sandbox can find the interpreter. Returns the actual
/// binary to exec and the full argument list.
///
/// Example: bin_path = `/home/agent/hermes-agent/.venv/bin/hermes`
///   shebang: `#!/home/ubuntu/hermes-agent/.venv/bin/python`
///   → exec_bin = `/home/agent/hermes-agent/.venv/bin/python`
///   → args = [exec_bin, bin_path, ...original_args]
fn rewrite_shebang_if_needed(bin_path: &str, original_args: &[String]) -> (String, Vec<String>) {
    // Try reading the first line to check for shebang.
    // This happens before fork, so Rust I/O is safe.
    if let Ok(content) = std::fs::read(bin_path) {
        if content.starts_with(b"#!") {
            if let Some(newline_pos) = content.iter().position(|&b| b == b'\n') {
                let shebang = String::from_utf8_lossy(&content[2..newline_pos]);
                let shebang = shebang.trim();
                // Check if shebang points to a home directory path
                if shebang.starts_with("/home/") && !shebang.starts_with("/home/agent/") {
                    let remapped = remap_path_for_sandbox(
                        std::path::Path::new(shebang.split_whitespace().next().unwrap_or(shebang)),
                        shebang,
                    );
                    // Return: exec_bin = remapped interpreter,
                    // args = [script_path, ...original_args] (no exec_bin — caller prepends argv[0])
                    let mut args = vec![bin_path.to_string()];
                    args.extend(original_args.iter().cloned());
                    return (remapped, args);
                }
            }
        }
    }
    // Not a script or shebang doesn't need rewriting — exec bin_path directly.
    (bin_path.to_string(), original_args.to_vec())
}

fn drop_all_capabilities() -> anyhow::Result<()> {
    // Capabilities to KEEP for filesystem access inside sandbox.
    // These allow root to bypass DAC permission checks (read/traverse).
    // All other capabilities (NET_ADMIN, SYS_ADMIN, MOUNT, etc.) are dropped.
    // Capability constants (linux/capability.h, not in libc crate)
    const CAP_DAC_OVERRIDE: u64 = 1; // bypass file read/write/exec perms
    const CAP_DAC_READ_SEARCH: u64 = 2; // bypass file read + dir search perms
    const CAP_FOWNER: u64 = 3; // bypass permission checks on file owner
    const CAP_CHOWN: u64 = 0; // change file ownership
    let keep: &[u64] = &[
        CAP_CHOWN,           // chown files in overlayfs (copy-up creates uid mismatch)
        CAP_DAC_OVERRIDE,    // bypass file read/write/exec perms
        CAP_DAC_READ_SEARCH, // bypass file read + dir search perms
        CAP_FOWNER,          // bypass permission checks requiring file owner match (chmod, etc.)
    ];

    for cap in 0..64u64 {
        if keep.contains(&cap) {
            continue;
        }
        // SAFETY: prctl(PR_CAPBSET_DROP, ...) takes only integer arguments
        // and modifies the calling process's capability bounding set; no
        // pointers are dereferenced. EINVAL on out-of-range capabilities is
        // expected and ignored below.
        let ret = unsafe { libc::prctl(libc::PR_CAPBSET_DROP, cap as libc::c_ulong, 0, 0, 0) };
        if ret < 0 {
            let err = std::io::Error::last_os_error();
            if err.raw_os_error() != Some(libc::EINVAL) {
                return Err(anyhow::anyhow!(
                    "Failed to drop capability {}: {}",
                    cap,
                    err
                ));
            }
        }
    }
    Ok(())
}

/// Termination-signal handler shared by SIGTERM, SIGINT, and SIGHUP.
/// Async-signal-safe: only writes to two atomics.
/// The waitpid polling loop checks TERMINATION_FLAG every 200ms and, on
/// transition to true, kills the sandbox child and falls through to the
/// cleanup stage. TERMINATION_SIGNAL records which of the three signals
/// fired so the CLI can print an accurate diagnostic.
extern "C" fn termination_flag_handler(sig: libc::c_int) {
    // Async-signal-safe: AtomicBool/AtomicI32 store with Relaxed is safe
    // from signal handlers.
    TERMINATION_SIGNAL.store(sig, std::sync::atomic::Ordering::Relaxed);
    TERMINATION_FLAG.store(true, std::sync::atomic::Ordering::Relaxed);
}

/// Global termination flag — set by SIGTERM/SIGINT/SIGHUP handlers,
/// checked by the sandbox waitpid loop to trigger graceful teardown.
static TERMINATION_FLAG: std::sync::atomic::AtomicBool = std::sync::atomic::AtomicBool::new(false);

/// The signal number that most recently tripped the termination handler.
/// Read when classifying the exit reason so the CLI can distinguish
/// SIGINT (user Ctrl+C) from SIGTERM (systemd) from SIGHUP (SSH disconnect).
static TERMINATION_SIGNAL: std::sync::atomic::AtomicI32 = std::sync::atomic::AtomicI32::new(0);
