//! Main sandbox orchestration: clone, setup, exec.
//!
//! Coordinates namespace creation, mount setup, network configuration,
//! and seccomp application into a single launch sequence.

use crate::capability::which_interpreter;
use crate::ebpf::{self, EbpfAttachResult};
use crate::mount::setup_mount_namespace;
use crate::namespace::{
    coordination_pipe, sandbox_clone_flags, signal_child_ready, wait_for_parent, write_uid_map,
};
use crate::network::{
    cleanup_host_network, clear_sandbox_state, record_sandbox_state, setup_host_network,
    setup_sandbox_network, VethConfig,
};
use crate::seccomp::{apply_seccomp_filter, count_seccomp_violations};
use crate::{SandboxConfig, SandboxResult};
use anyhow::{Context, Result};
use nix::sys::wait::{waitpid, WaitStatus};
use std::path::PathBuf;

/// Stack size for the cloned child process (2 MB).
const CHILD_STACK_SIZE: usize = 2 * 1024 * 1024;

/// Launch an agent inside a fully isolated Linux sandbox.
pub fn launch(config: SandboxConfig) -> Result<SandboxResult> {
    let start = std::time::Instant::now();

    // Pre-flight: defensive cleanup of orphaned sandbox resources from previous runs.
    // This prevents stale iptables FORWARD chains or veth interfaces from polluting
    // the host network. Particularly important after SIGKILL'd sandboxes where RAII
    // guards did not run.
    if let Err(e) = crate::network::cleanup_all_orphans() {
        tracing::debug!(error = %e, "Orphan cleanup failed (non-fatal)");
    }

    // Pre-flight: resolve interpreter path
    let interpreter_path = which_interpreter(&config.interpreter)
        .with_context(|| format!("Interpreter '{}' not found in PATH", config.interpreter))?;

    // CA certificate for MITM trust store injection.
    // The CA is generated by the proxy process (main.rs) which holds the private key.
    // The sandbox only receives the public certificate via SandboxConfig.mitm_ca_cert,
    // downloaded from GET /gvm/ca.pem by the CLI before sandbox launch.
    // This ensures: (1) CA matches the MITM listener's signing key, (2) private key
    // never enters the sandbox namespace.
    let ca_cert_pem: Option<Vec<u8>> = config.mitm_ca_cert.clone();

    // Pre-resolve lib-dynload dependencies in the PARENT process.
    // Running ldd from PID 1 of a new PID namespace triggers kernel panic on 6.17.0-1009-aws.
    let extra_lib_paths = if std::env::var("GVM_DEBUG_SKIP_DYNLOAD").is_ok() {
        Vec::new()
    } else {
        crate::mount::resolve_dynload_libs(&interpreter_path)
    };

    // Pre-mount workspace in parent process BEFORE clone().
    // Kernel 6.17+ blocks bind-mount of host paths inside user namespaces.
    // By mounting in the parent (which has real root), the mount is visible
    // to the child's mount namespace via inheritance.
    // Use PID-based unique paths to prevent race conditions when multiple
    // sandboxes start concurrently. Previous hardcoded paths caused mount
    // collisions: sandbox A mounts → sandbox B umounts A's mount → A's child
    // sees empty root.
    let my_pid = std::process::id();
    let staging_ws = std::path::PathBuf::from(format!("/tmp/gvm-sandbox-staging-ws-{}", my_pid));
    let sandbox_root = std::path::PathBuf::from(format!("/tmp/gvm-sandbox-root-{}", my_pid));
    // Clean up any stale mounts from a previous crashed run.
    // umount2 with MNT_DETACH handles the recursive case (nested mounts).
    nix::mount::umount2(&sandbox_root, nix::mount::MntFlags::MNT_DETACH).ok();
    std::fs::remove_dir_all(&sandbox_root).ok();
    nix::mount::umount(&staging_ws).ok();
    std::fs::create_dir_all(&staging_ws).context("Failed to create workspace staging directory")?;
    nix::mount::mount(
        Some(&config.workspace_dir),
        &staging_ws,
        None::<&str>,
        nix::mount::MsFlags::MS_BIND | nix::mount::MsFlags::MS_REC,
        None::<&str>,
    )
    .with_context(|| {
        format!(
            "Failed to pre-mount workspace in parent: {} → {}",
            config.workspace_dir.display(),
            staging_ws.display()
        )
    })?;

    // Create coordination pipe
    let (parent_fd, child_fd) = coordination_pipe()?;

    // Allocate child stack
    let mut stack = vec![0u8; CHILD_STACK_SIZE];
    let clone_flags = sandbox_clone_flags();

    // Prepare data for the child closure
    let child_config = config.clone();
    let child_interpreter_path = interpreter_path.clone();
    let child_ca_pem = ca_cert_pem.clone();
    let child_extra_libs = extra_lib_paths;

    let child_pid = unsafe {
        nix::sched::clone(
            Box::new(move || {
                // ── Child process (inside new namespaces) ──
                child_entry(
                    child_fd,
                    &child_config,
                    &child_interpreter_path,
                    child_ca_pem.as_deref(),
                    &child_extra_libs,
                )
            }),
            &mut stack,
            clone_flags,
            Some(nix::sys::signal::SIGCHLD as i32),
        )
    }
    .context("clone() failed — ensure user namespaces are enabled")?;

    tracing::info!(
        child_pid = child_pid.as_raw(),
        "Sandbox child process created"
    );

    // ── Parent process: set up UID mapping and network ──

    // 1. Write UID/GID mapping (only needed when CLONE_NEWUSER is active)
    if !nix::unistd::geteuid().is_root() {
        write_uid_map(child_pid)?;
    }

    // 2. Set up veth network pair
    let veth_config = VethConfig::from_pid(child_pid.as_raw() as u32, config.proxy_addr);
    let network_result = setup_host_network(&veth_config);

    // dns_target is recorded in state file for deterministic cleanup.
    // If DNS changes between setup and cleanup (DHCP renewal), cleanup
    // still deletes the exact DNAT rule that was created.
    let dns_target = match &network_result {
        Ok(dns) => Some(dns.clone()),
        Err(e) => {
            tracing::warn!(error = %e, "Host network setup failed — sandbox will have no network");
            None
        }
    };

    if network_result.is_ok() {
        let mount_paths = vec![staging_ws.clone(), sandbox_root.clone()];
        if let Err(e) =
            record_sandbox_state(&veth_config, &mount_paths, None, dns_target.as_deref())
        {
            tracing::debug!(error = %e, "Failed to record sandbox state (orphan cleanup unavailable)");
        }
    }
    // 2.5. Attach TC ingress filter on host-side veth (unbypassable enforcement)
    //      This runs BEFORE signaling the child, so enforcement is active from first packet.
    //      If TC filter is unavailable, iptables provides baseline enforcement and
    //      seccomp AF_NETLINK blocking prevents iptables modification (defense-in-depth).
    // RAII guard: dropping this detaches the TC filter. Kept alive for sandbox duration.
    let _ebpf_guard = if network_result.is_ok() {
        let proxy_ip: std::net::Ipv4Addr = veth_config
            .host_ip
            .parse()
            .unwrap_or(std::net::Ipv4Addr::new(10, 200, 0, 1));
        match ebpf::try_attach_tc_filter(
            &veth_config.host_iface,
            proxy_ip,
            veth_config.proxy_addr.port(),
        ) {
            EbpfAttachResult::Attached { interface, guard } => {
                tracing::info!(
                    interface = %interface,
                    "TC ingress filter ACTIVE — unbypassable proxy enforcement"
                );
                Some(guard)
            }
            EbpfAttachResult::Unavailable { reason } => {
                tracing::warn!(
                    reason = %reason,
                    "TC ingress filter unavailable — using iptables with seccomp defense-in-depth"
                );
                None
            }
        }
    } else {
        None
    };

    // 2.7. Set up cgroup resource limits (if configured)
    let _cgroup_guard = if config.memory_limit.is_some() || config.cpu_limit.is_some() {
        match crate::cgroup::CgroupGuard::create(
            child_pid.as_raw() as u32,
            config.memory_limit,
            config.cpu_limit,
        ) {
            Ok(guard) => {
                // Update state file with cgroup path
                if let Some(ref g) = guard {
                    let mount_paths = vec![staging_ws.clone(), sandbox_root.clone()];
                    let cgroup_path = format!("/sys/fs/cgroup/gvm-agent-{}", child_pid.as_raw());
                    if let Err(e) = record_sandbox_state(
                        &veth_config,
                        &mount_paths,
                        Some(&cgroup_path),
                        dns_target.as_deref(),
                    ) {
                        tracing::debug!(error = %e, "Failed to update state with cgroup");
                    }
                    let _ = g; // suppress unused warning
                }
                guard
            }
            Err(e) => {
                tracing::warn!(error = %e, "cgroup setup failed — continuing without resource limits");
                None
            }
        }
    } else {
        None
    };

    // 3. Signal child that setup is complete
    signal_child_ready(parent_fd, child_pid.as_raw() as u32)?;

    let setup_ms = start.elapsed().as_millis() as u64;
    tracing::info!(
        setup_ms = setup_ms,
        "Sandbox setup complete, waiting for agent"
    );

    // 3.5. TLS uprobe (experimental, observation-only — gated behind `uprobe` feature flag)
    //
    // The uprobe attaches to SSL_write_ex and captures plaintext before encryption.
    // MITM (transparent TLS proxy on port 8443) is the primary HTTPS inspection mechanism.
    // The uprobe is an optional defense-in-depth layer for environments where MITM is not
    // available or as a secondary observation channel.
    //
    // Enable at compile time: cargo build --features uprobe
    #[cfg(feature = "uprobe")]
    let _tls_probe_handle = {
        let child_raw = child_pid.as_raw() as u32;
        let probe_mode = &config.tls_probe_mode;
        let audit_only = matches!(probe_mode, crate::TlsProbeMode::Audit);
        let disabled = matches!(probe_mode, crate::TlsProbeMode::Disabled);

        if disabled {
            tracing::debug!("TLS probe disabled by config");
            None
        } else {
            std::thread::sleep(std::time::Duration::from_millis(500));

            let policy_callback: crate::tls_probe::PolicyCheckFn = if let Some(ref proxy_url) =
                config.proxy_url
            {
                let check_url = format!("{}/gvm/check", proxy_url.trim_end_matches('/'));
                let agent = ureq::AgentBuilder::new()
                    .timeout_connect(std::time::Duration::from_millis(50))
                    .timeout_read(std::time::Duration::from_millis(50))
                    .timeout_write(std::time::Duration::from_millis(50))
                    .build();
                Box::new(move |method: &str, host: &str, path: &str| {
                    let body = serde_json::json!({
                        "method": method,
                        "target_host": host,
                        "target_path": path,
                        "operation": "uprobe",
                    });
                    match agent
                        .post(&check_url)
                        .set("Content-Type", "application/json")
                        .set("X-GVM-Uprobe-Token", "internal")
                        .send_string(&body.to_string())
                    {
                        Ok(resp) => {
                            let text = resp.into_string().unwrap_or_default();
                            if let Ok(json) = serde_json::from_str::<serde_json::Value>(&text) {
                                let decision = json
                                    .get("decision")
                                    .and_then(|v| v.as_str())
                                    .unwrap_or("Deny");
                                match decision {
                                    d if d.contains("Allow") => {
                                        crate::tls_probe::PolicyDecision::Allow
                                    }
                                    d if d.contains("Delay") => {
                                        let ms = json
                                            .get("delay_ms")
                                            .and_then(|v| v.as_u64())
                                            .unwrap_or(300);
                                        crate::tls_probe::PolicyDecision::Delay { milliseconds: ms }
                                    }
                                    _ => {
                                        let reason = json
                                            .get("next_action")
                                            .and_then(|v| v.as_str())
                                            .unwrap_or("blocked by policy")
                                            .to_string();
                                        crate::tls_probe::PolicyDecision::Deny { reason }
                                    }
                                }
                            } else {
                                crate::tls_probe::PolicyDecision::Deny {
                                    reason: "uprobe: unparseable proxy response".into(),
                                }
                            }
                        }
                        Err(_e) => crate::tls_probe::PolicyDecision::Deny {
                            reason: "uprobe: proxy unreachable — fail-closed".into(),
                        },
                    }
                })
            } else {
                Box::new(|_method: &str, _host: &str, _path: &str| {
                    crate::tls_probe::PolicyDecision::Allow
                })
            };

            match crate::tls_probe::start_tls_probe_thread(child_raw, policy_callback, audit_only) {
                Ok(handle) => {
                    let mode = if audit_only { "audit" } else { "enforce" };
                    tracing::info!(pid = child_raw, mode, "TLS uprobe started (experimental)");
                    Some(handle)
                }
                Err(e) => {
                    tracing::debug!(
                        pid = child_raw, error = %e,
                        "TLS probe not available — MITM is primary HTTPS inspection"
                    );
                    None
                }
            }
        }
    };
    #[cfg(not(feature = "uprobe"))]
    let _tls_probe_handle: Option<()> = None;

    // 4. Wait for child to exit with timeout + SIGTERM awareness.
    //
    // The WNOHANG polling loop serves three purposes:
    // a) Timeout: kill child after GVM_SANDBOX_TIMEOUT
    // b) SIGTERM: detect parent's pending termination via SIGTERM flag
    // c) Cleanup guarantee: always reach cleanup code (step 5) even if
    //    the tokio runtime is shutting down, because this runs in spawn_blocking
    //
    // SIGTERM detection: we install a signal flag that the polling loop checks.
    // When SIGTERM is received (Ctrl+C, systemd stop, stress-test kill), we
    // kill the child and proceed to cleanup — preventing orphan veths.
    use std::sync::atomic::Ordering;

    // Install SIGTERM handler (sets SIGTERM_FLAG atomic bool)
    SIGTERM_FLAG.store(false, Ordering::Relaxed); // Reset for this sandbox run
    unsafe {
        libc::signal(
            libc::SIGTERM,
            sigterm_flag_handler as *const () as libc::sighandler_t,
        );
    }

    let wait_timeout = std::time::Duration::from_secs(
        std::env::var("GVM_SANDBOX_TIMEOUT")
            .ok()
            .and_then(|s| s.parse().ok())
            .unwrap_or(3600), // Default: 1 hour
    );
    let wait_start = std::time::Instant::now();
    let wait_result = loop {
        match waitpid(child_pid, Some(nix::sys::wait::WaitPidFlag::WNOHANG)) {
            Ok(WaitStatus::StillAlive) => {
                // Check SIGTERM — kill child gracefully and proceed to cleanup
                if SIGTERM_FLAG.load(Ordering::Relaxed) {
                    tracing::info!(
                        pid = child_pid.as_raw(),
                        "SIGTERM received — killing sandbox child for cleanup"
                    );
                    nix::sys::signal::kill(child_pid, nix::sys::signal::SIGTERM).ok();
                    std::thread::sleep(std::time::Duration::from_millis(500));
                    nix::sys::signal::kill(child_pid, nix::sys::signal::SIGKILL).ok();
                    break waitpid(child_pid, None);
                }

                // timeout=0 means no timeout (persistent sandbox).
                // Agent runs until it exits or SIGTERM is received.
                if wait_timeout.as_secs() > 0 && wait_start.elapsed() > wait_timeout {
                    tracing::warn!(
                        pid = child_pid.as_raw(),
                        timeout_secs = wait_timeout.as_secs(),
                        "Sandbox child timed out — sending SIGKILL"
                    );
                    nix::sys::signal::kill(child_pid, nix::sys::signal::SIGKILL).ok();
                    break waitpid(child_pid, None);
                }
                std::thread::sleep(std::time::Duration::from_millis(200));
                continue;
            }
            result => break result,
        }
    };
    let seccomp_violations = match &wait_result {
        Ok(status) => count_seccomp_violations(status),
        Err(_) => 0,
    };

    let exit_code = match wait_result {
        Ok(WaitStatus::Exited(_, code)) => code,
        Ok(WaitStatus::Signaled(_, signal, _)) => {
            tracing::warn!(signal = ?signal, "Agent killed by signal");
            128 + signal as i32
        }
        Ok(status) => {
            tracing::warn!(status = ?status, "Unexpected wait status");
            1
        }
        Err(e) => {
            tracing::error!(error = %e, "waitpid failed");
            1
        }
    };

    if seccomp_violations > 0 {
        tracing::error!(
            violations = seccomp_violations,
            child_pid = child_pid.as_raw(),
            "Seccomp violations detected — agent attempted blocked syscall(s). \
             Check 'dmesg | grep SECCOMP' or 'ausearch -m SECCOMP' for details."
        );
    }

    // 5. Scan overlayfs upper layer BEFORE cleanup (tmpfs umount destroys it).
    // This must happen while the overlay is still mounted so files are accessible.
    let fs_diff = {
        let upper_dir = sandbox_root.join("gvm-overlay/upper");
        if upper_dir.exists() {
            let policy = config.fs_policy.as_ref().cloned().unwrap_or_default();
            match crate::filesystem::scan_upper_layer(&upper_dir, &config.workspace_dir, &policy) {
                Ok(report) => {
                    // Execute auto-merge (Created files only — Modified goes to ManualCommit)
                    if !report.auto_merged.is_empty() {
                        let merge_result = crate::filesystem::execute_merge(
                            &report,
                            &upper_dir,
                            &config.workspace_dir,
                        );
                        tracing::info!(
                            copied = merge_result.copied.len(),
                            skipped = merge_result.skipped.len(),
                            errors = merge_result.errors.len(),
                            "Overlayfs auto-merge completed"
                        );
                    }

                    // Stage needs_review files to persistent storage (before umount).
                    // The interactive review prompt runs in the CLI layer (pipeline.rs)
                    // AFTER sandbox cleanup, so files must be preserved outside tmpfs.
                    if !report.needs_review.is_empty() {
                        let staging_dir =
                            PathBuf::from(format!("data/sandbox-staging/{}", std::process::id()));
                        if std::fs::create_dir_all(&staging_dir).is_ok() {
                            for f in &report.needs_review {
                                let src = upper_dir.join(&f.path);
                                let dst = staging_dir.join(&f.path);
                                if let Some(parent) = dst.parent() {
                                    std::fs::create_dir_all(parent).ok();
                                }
                                std::fs::copy(&src, &dst).ok();
                            }
                            tracing::debug!(
                                count = report.needs_review.len(),
                                staging = %staging_dir.display(),
                                "Staged needs_review files for interactive review"
                            );
                        }
                    }

                    Some(report)
                }
                Err(e) => {
                    tracing::debug!(error = %e, "Overlayfs scan failed (non-fatal)");
                    None
                }
            }
        } else {
            None
        }
    };

    // 6. Clean up host-side resources
    // Unmount sandbox root (lazy detach handles nested mounts from failed runs)
    nix::mount::umount2(&sandbox_root, nix::mount::MntFlags::MNT_DETACH).ok();
    std::fs::remove_dir_all(&sandbox_root).ok();
    // Unmount the staging workspace (pre-mounted before clone for kernel 6.17+ compat)
    nix::mount::umount(&staging_ws).ok();
    std::fs::remove_dir(&staging_ws).ok();

    // Drop TC filter guard first — this detaches the filter via RAII Drop.
    // Must happen before cleanup_host_network which deletes the veth interface.
    drop(_ebpf_guard);

    if network_result.is_ok() {
        cleanup_host_network(&veth_config, dns_target.as_deref());
        clear_sandbox_state();
    }

    Ok(SandboxResult {
        exit_code,
        setup_ms,
        seccomp_violations,
        fs_diff,
    })
}

/// Child process entry point (runs inside new namespaces).
fn child_entry(
    coord_fd: std::os::unix::io::RawFd,
    config: &SandboxConfig,
    interpreter_path: &std::path::Path,
    ca_cert_pem: Option<&[u8]>,
    extra_lib_paths: &[std::path::PathBuf],
) -> isize {
    // Wait for parent to complete UID mapping and network setup
    let network_seed = match wait_for_parent(coord_fd) {
        Ok(seed) => seed,
        Err(e) => {
            eprintln!("gvm-sandbox: coordination failed: {}", e);
            return 1;
        }
    };
    // Use parent-provided seed so interface names/IPs match host-side setup.
    let veth_config = VethConfig::from_pid(network_seed, config.proxy_addr);

    // Set up network inside the sandbox
    if let Err(e) = setup_sandbox_network(&veth_config) {
        // Network failure is non-fatal for debugging — agent just won't have connectivity
        eprintln!("gvm-sandbox: network setup failed (non-fatal): {}", e);
        eprintln!("  Hint: ensure ip_forward=1 (sudo sysctl net.ipv4.ip_forward=1),");
        eprintln!("  iptables installed, and running with sudo (CAP_NET_ADMIN required).");
        eprintln!("  Agent will run without network connectivity.");
    }

    // Set up mount namespace (pivot_root)
    // DNS server must match the OUTPUT iptables rule (host veth IP)
    if let Err(e) = setup_mount_namespace(
        &config.workspace_dir,
        interpreter_path,
        &veth_config.host_ip,
        ca_cert_pem,
        config.fs_policy.as_ref(),
        extra_lib_paths,
        &config.sandbox_profile,
    ) {
        eprintln!("gvm-sandbox: mount namespace setup failed: {:#}", e);
        eprintln!("  Hint: this usually means the interpreter binary or its shared");
        eprintln!(
            "  libraries cannot be bind-mounted. Check that '{}' exists",
            config.interpreter
        );
        eprintln!("  and 'ldd {}' succeeds.", interpreter_path.display());
        return 1;
    }

    // Drop all capabilities from the bounding set.
    if let Err(e) = drop_all_capabilities() {
        eprintln!("gvm-sandbox: capability drop failed: {}", e);
        eprintln!("  Hint: this is unusual. Check kernel capabilities support.");
        return 1;
    }
    // Apply seccomp-BPF filter (must be last before exec)
    if let Err(e) = apply_seccomp_filter(&config.seccomp_profile) {
        eprintln!("gvm-sandbox: seccomp filter failed: {}", e);
        eprintln!("  Hint: seccomp-BPF requires kernel 3.17+. Check 'grep SECCOMP /boot/config-$(uname -r)'.");
        return 1;
    }
    // Prepare environment variables
    let proxy_url = format!(
        "http://{}:{}",
        veth_config.host_ip,
        config.proxy_addr.port()
    );

    // Build exec arguments
    let interpreter_name = interpreter_path
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or(&config.interpreter);

    let bin_path = format!("/bin/{}", interpreter_name);

    // Set environment and exec
    std::env::set_var("HTTP_PROXY", &proxy_url);
    std::env::set_var("http_proxy", &proxy_url);
    if ca_cert_pem.is_some() {
        // MITM active: don't set HTTPS_PROXY — DNAT handles 443→MITM
        std::env::remove_var("HTTPS_PROXY");
        std::env::remove_var("https_proxy");
    } else {
        // --no-mitm: set HTTPS_PROXY for CONNECT relay (domain-level only)
        std::env::set_var("HTTPS_PROXY", &proxy_url);
        std::env::set_var("https_proxy", &proxy_url);
    }
    std::env::set_var("GVM_AGENT_ID", &config.agent_id);
    std::env::set_var("GVM_PROXY_URL", &proxy_url);
    // HOME points to the overlayfs-merged home directory.
    // Agent reads config from host's $HOME (lower layer), writes go to tmpfs
    // (upper layer) and vanish on sandbox exit. Sensitive dirs (.ssh, .aws)
    // are masked with empty tmpfs.
    std::env::set_var("HOME", "/home/agent");
    std::env::set_var("TMPDIR", "/tmp");
    // Disable io_uring in Node.js — forces epoll fallback.
    // io_uring syscalls are not in seccomp whitelist (CVE history).
    // Performance difference is negligible for agent workloads.
    std::env::set_var("UV_USE_IO_URING", "0");

    // NOTE: sandbox inherits ALL parent env vars via clone().
    // If ANTHROPIC_API_KEY etc. are in the parent process, they're available in sandbox.
    // sudo -E may NOT preserve env (sudoers env_reset). Use:
    //   sudo env ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY gvm run --sandbox ...

    // CA trust store env vars (for transparent MITM in sandbox)
    if ca_cert_pem.is_some() {
        let ca_path = "/etc/ssl/certs/gvm-ca.crt";
        std::env::set_var("SSL_CERT_FILE", ca_path);
        std::env::set_var("REQUESTS_CA_BUNDLE", ca_path);
        std::env::set_var("NODE_EXTRA_CA_CERTS", ca_path);
        std::env::set_var("CURL_CA_BUNDLE", ca_path);
    }

    // Build argv: [interpreter, ...args]
    let c_bin = std::ffi::CString::new(bin_path.clone()).unwrap();
    let mut c_args: Vec<std::ffi::CString> = vec![c_bin.clone()];
    for arg in &config.interpreter_args {
        c_args.push(std::ffi::CString::new(arg.as_str()).unwrap());
    }

    // ── PID 1 init reaper ──
    //
    // SAFETY INVARIANT (fork + async-signal-safety):
    // After fork(), both child and PID 1 parent MUST only call async-signal-safe
    // functions until exec (child) or _exit (PID 1). This means:
    // - NO Rust heap allocation (no Vec, String, Box, println!, format!)
    // - NO tracing macros (tracing::info! etc. — these allocate)
    // - NO mutex/lock acquisition
    // - NO File I/O via Rust std (only libc::write to fd 2 is safe)
    // Only libc functions listed in signal-safety(7) are permitted.
    // Currently: eprintln! (before fork), waitpid/WIFEXITED/_exit (after fork).
    // Adding any Rust runtime calls to the PID 1 loop WILL cause UB.
    //
    // We are PID 1 inside CLONE_NEWPID. If we exec directly, the agent
    // interpreter becomes PID 1 but does NOT reap orphaned children.
    // When the agent spawns subprocesses (subprocess.Popen, child_process.exec)
    // that exit, they become zombies (Z state). Eventually the PID table fills
    // and the agent can't fork at all.
    //
    // Fix: fork(). The child execs the agent. This process (PID 1) stays alive
    // as a minimal init: it loops on waitpid(-1) to reap ANY child (including
    // orphans reparented to PID 1), and exits with the agent's exit code.
    //
    // This is equivalent to tini/dumb-init but without an external dependency.
    match unsafe { libc::fork() } {
        -1 => {
            // SAFETY: After fork(), only async-signal-safe functions are permitted.
            // Use libc::write to fd 2 (stderr) instead of eprintln! (which allocates).
            unsafe {
                let msg = b"gvm-sandbox: fork() for init reaper failed\n";
                libc::write(2, msg.as_ptr() as *const libc::c_void, msg.len());
            }
            1
        }
        0 => {
            // ── Child: exec the agent ──
            match nix::unistd::execv(&c_bin, &c_args) {
                Ok(_) => unreachable!(),
                Err(_) => {
                    // SAFETY: After fork(), only async-signal-safe.
                    unsafe {
                        let msg = b"gvm-sandbox: exec failed\n";
                        libc::write(2, msg.as_ptr() as *const libc::c_void, msg.len());
                        libc::_exit(1);
                    }
                }
            }
        }
        agent_pid => {
            // ── PID 1 (init reaper): wait for agent + reap orphans ──
            //
            // After the agent exits, its sub-processes (OpenClaw gateway workers,
            // Node.js worker threads, detached children) may still be alive.
            // Without killing them, waitpid(-1) blocks forever — the parent's
            // WNOHANG loop never sees PID 1 exit, causing the sandbox to hang.
            //
            // Fix: once agent exits, SIGTERM → sleep → SIGKILL all remaining
            // children, then continue reaping until ECHILD.
            let mut agent_exit_code: i32 = 1;
            let mut agent_exited = false;

            loop {
                let mut status: i32 = 0;
                let pid = unsafe { libc::waitpid(-1, &mut status, 0) };
                if pid < 0 {
                    // ECHILD: no more children — all reaped
                    break;
                }
                if pid == agent_pid {
                    // Agent exited — record exit code
                    if libc::WIFEXITED(status) {
                        agent_exit_code = libc::WEXITSTATUS(status);
                    } else if libc::WIFSIGNALED(status) {
                        agent_exit_code = 128 + libc::WTERMSIG(status);
                    }
                    agent_exited = true;

                    // Kill all remaining children in this PID namespace.
                    // kill(-1, sig) sends to all processes except PID 1 (us).
                    // SAFETY: async-signal-safe (kill, nanosleep, write are all safe).
                    unsafe {
                        libc::kill(-1, libc::SIGTERM);
                        // Brief grace period for clean shutdown
                        let ts = libc::timespec {
                            tv_sec: 0,
                            tv_nsec: 500_000_000, // 500ms
                        };
                        libc::nanosleep(&ts, std::ptr::null_mut());
                        libc::kill(-1, libc::SIGKILL);
                    }
                    // Continue reaping until ECHILD
                }
                // Any other PID: orphaned/killed child reaped.
            }

            // Use _exit to avoid running Rust destructors in the clone'd process.
            unsafe { libc::_exit(agent_exit_code) };
        }
    }
}

/// Drop all capabilities from the bounding set.
///
/// After mount/network setup completes, capabilities are no longer needed.
/// Dropping them prevents the sandboxed agent from using iptables, mounting
/// filesystems, loading kernel modules, etc. — even when running as root.
fn drop_all_capabilities() -> anyhow::Result<()> {
    // Linux capability IDs range from 0 to CAP_LAST_CAP.
    // As of Linux 6.x, CAP_LAST_CAP is ~41. We iterate to 64 for future-proofing;
    // prctl returns EINVAL for non-existent caps, which we safely ignore.
    for cap in 0..64u64 {
        let ret = unsafe { libc::prctl(libc::PR_CAPBSET_DROP, cap as libc::c_ulong, 0, 0, 0) };
        if ret < 0 {
            let err = std::io::Error::last_os_error();
            if err.raw_os_error() != Some(libc::EINVAL) {
                return Err(anyhow::anyhow!(
                    "Failed to drop capability {}: {}",
                    cap,
                    err
                ));
            }
            // EINVAL = capability doesn't exist — expected for cap > CAP_LAST_CAP
        }
    }
    Ok(())
}

/// SIGTERM handler that sets an atomic flag.
/// Async-signal-safe: only writes to an atomic bool.
/// The waitpid polling loop checks this flag every 200ms.
extern "C" fn sigterm_flag_handler(_sig: libc::c_int) {
    // Async-signal-safe: AtomicBool::store with Relaxed is safe from signal handlers.
    // SIGTERM_FLAG is a module-level static checked by the waitpid polling loop.
    SIGTERM_FLAG.store(true, std::sync::atomic::Ordering::Relaxed);
}

/// Global SIGTERM flag — checked by sandbox waitpid loop.
static SIGTERM_FLAG: std::sync::atomic::AtomicBool = std::sync::atomic::AtomicBool::new(false);
